import React,{useEffect,useMemo,useRef,useState} from "react";
import {useNavigate} from "react-router-dom";
import {api} from "../api";
import {ArrowRight,Copy,Heart,LogOut,MapPin,Package,RefreshCw,ShieldCheck,Star,UserRound} from "lucide-react";
import "../account.css";

const money=n=>`₹${Number(n||0).toLocaleString("en-IN")}`;
const emptyAddress={label:"HOME",name:"",phone:"",address:"",city:"",state:"Karnataka",pincode:"",is_default:false};

export default function Account({user,setUser,orders=[]}){
 const nav=useNavigate();
 const [mode,setMode]=useState(user?"profile":"login"),[tab,setTab]=useState("overview"),[f,setF]=useState({name:"",email:"",password:"",referral_code:""});
 const [address,setAddress]=useState(emptyAddress),[addresses,setAddresses]=useState([]),[editing,setEditing]=useState(null),[profile,setProfile]=useState(null);
 const [busy,setBusy]=useState(false),[addressBusy,setAddressBusy]=useState(false),[err,setErr]=useState(""),[notice,setNotice]=useState(""),[forgot,setForgot]=useState(false),[forgotEmail,setForgotEmail]=useState("");
 const [returns,setReturns]=useState([]);
 const [editProfile,setEditProfile]=useState(false),[pf,setPf]=useState({name:"",email:"",current_password:"",new_password:""}),[pfBusy,setPfBusy]=useState(false),[pfErr,setPfErr]=useState("");
 const [deleteOpen,setDeleteOpen]=useState(false),[deletePassword,setDeletePassword]=useState(""),[deleteBusy,setDeleteBusy]=useState(false),[deleteErr,setDeleteErr]=useState("");
 useEffect(()=>{if(!user)return;let cancelled=false;setBusy(true);Promise.all([api("/auth/me"),api("/profile/addresses"),api("/returns/mine").catch(()=>[])]).then(([me,addrs,rets])=>{if(!cancelled){setProfile(me);setAddresses(Array.isArray(addrs)?addrs:[]);setReturns(Array.isArray(rets)?rets:[]);}}).catch(e=>{if(!cancelled)setNotice(e.message||"Unable to load account details")}).finally(()=>{if(!cancelled)setBusy(false)});return()=>{cancelled=true}},[user]);
 const persist=(u,token)=>{localStorage.setItem("offgrid_user",JSON.stringify(u));if(token)localStorage.setItem("offgrid_token",token);setUser(u);setProfile(p=>({...p,...u}))};
 const login=async e=>{e.preventDefault();setBusy(true);setErr("");try{const r=await api("/auth/login",{method:"POST",body:JSON.stringify({email:f.email.trim(),password:f.password})});persist(r.user,r.token);setMode("profile")}catch(e){setErr(e.message||"Login failed")}finally{setBusy(false)}};
 const register=async e=>{e.preventDefault();setBusy(true);setErr("");try{const r=await api("/auth/register",{method:"POST",body:JSON.stringify({name:f.name.trim(),email:f.email.trim(),password:f.password,referral_code:f.referral_code||undefined})});persist(r.user,r.token);setMode("profile")}catch(e){setErr(e.message||"Registration failed")}finally{setBusy(false)}};
 const googleDivRef=useRef(null);
 const handleGoogleCredential=async(response)=>{setBusy(true);setErr("");try{const r=await api("/auth/google",{method:"POST",body:JSON.stringify({credential:response.credential})});persist(r.user,r.token);setMode("profile")}catch(e){setErr(e.message||"Google sign-in failed")}finally{setBusy(false)}};
 useEffect(()=>{
  const clientId=import.meta.env.VITE_GOOGLE_CLIENT_ID;
  if(!clientId||mode==="profile"||forgot)return;
  let cancelled=false,tries=0;
  const tryInit=()=>{
   if(cancelled)return;
   if(window.google?.accounts?.id&&googleDivRef.current){
    window.google.accounts.id.initialize({client_id:clientId,callback:handleGoogleCredential});
    googleDivRef.current.innerHTML="";
    window.google.accounts.id.renderButton(googleDivRef.current,{theme:"filled_black",size:"large",width:330,text:mode==="register"?"signup_with":"signin_with"});
   }else if(tries<20){tries++;setTimeout(tryInit,250)}
  };
  tryInit();
  return()=>{cancelled=true};
 },[mode,forgot]);
 const signOut=()=>{localStorage.removeItem("offgrid_user");localStorage.removeItem("offgrid_token");setUser(null);setMode("login");setProfile(null);setAddresses([])};
 const refreshAccount=async()=>{try{const [me,addrs]=await Promise.all([api("/auth/me"),api("/profile/addresses")]);setProfile(me);setAddresses(Array.isArray(addrs)?addrs:[]);setUser(u=>({...u,...me}));localStorage.setItem("offgrid_user",JSON.stringify({...user,...me}))}catch(e){setNotice(e.message||"Could not refresh account")}};
 const startAddress=item=>{setEditing(item?.id||null);setAddress(item?{...item}:emptyAddress);setNotice("");setTab("addresses")};
 const saveAddress=async e=>{e.preventDefault();setAddressBusy(true);setNotice("");try{const saved=editing?await api(`/profile/addresses/${editing}`,{method:"PATCH",body:JSON.stringify(address)}):await api("/profile/addresses",{method:"POST",body:JSON.stringify(address)});setAddresses(cur=>editing?cur.map(a=>a.id===saved.id?saved:a):[saved,...cur]);setEditing(null);setAddress(emptyAddress);setNotice("ADDRESS SAVED")}catch(e){setNotice(e.message||"Could not save address")}finally{setAddressBusy(false)}};
 const removeAddress=async id=>{if(!window.confirm("Remove this saved address?"))return;try{await api(`/profile/addresses/${id}`,{method:"DELETE"});setAddresses(cur=>cur.filter(a=>a.id!==id));setNotice("ADDRESS REMOVED")}catch(e){setNotice(e.message||"Could not remove address")}};
 const makeDefault=async id=>{try{const saved=await api(`/profile/addresses/${id}/default`,{method:"POST"});setAddresses(cur=>cur.map(a=>({...a,is_default:a.id===saved.id})));setNotice("DEFAULT ADDRESS UPDATED")}catch(e){setNotice(e.message||"Could not update default address")}};
 const sendReset=async e=>{e.preventDefault();setBusy(true);setErr("");try{const r=await api("/auth/forgot-password",{method:"POST",body:JSON.stringify({email:forgotEmail.trim()})});setNotice(r.message||"Check your email for reset instructions");setForgot(false)}catch(e){setErr(e.message||"Could not start password reset")}finally{setBusy(false)}};
 const copyReferral=async()=>{if(!profile?.referral_code)return;try{await navigator.clipboard.writeText(profile.referral_code);setNotice("REFERRAL CODE COPIED")}catch{setNotice(`YOUR REFERRAL CODE: ${profile.referral_code}`)}};
 const referralLink=profile?.referral_code?`${window.location.origin}/account?ref=${profile.referral_code}`:"";
 const shareReferralWhatsapp=()=>{if(!profile?.referral_code)return;const text=encodeURIComponent(`Shop THE OFF GRID and get a reward with my code ${profile.referral_code} — ${referralLink}`);window.open(`https://wa.me/?text=${text}`,"_blank")};
 const startEditProfile=()=>{setPf({name:profile?.name||user.name||"",email:profile?.email||user.email||"",current_password:"",new_password:""});setPfErr("");setEditProfile(true)};
 const saveProfile=async e=>{e.preventDefault();setPfBusy(true);setPfErr("");try{const body={};if(pf.name.trim()!==(profile?.name||""))body.name=pf.name.trim();if(pf.email.trim()!==(profile?.email||""))body.email=pf.email.trim();if(pf.new_password){body.new_password=pf.new_password;body.current_password=pf.current_password}if(!Object.keys(body).length){setEditProfile(false);setPfBusy(false);return}const updated=await api("/auth/me",{method:"PATCH",body:JSON.stringify(body)});setProfile(p=>({...p,...updated}));setUser(u=>({...u,...updated}));localStorage.setItem("offgrid_user",JSON.stringify({...user,...updated}));setEditProfile(false);setNotice("PROFILE UPDATED")}catch(e){setPfErr(e.message||"Could not update profile")}finally{setPfBusy(false)}};
 const deleteAccount=async e=>{e.preventDefault();setDeleteBusy(true);setDeleteErr("");try{await api("/auth/me",{method:"DELETE",body:JSON.stringify({password:deletePassword})});signOut();nav("/")}catch(e){setDeleteErr(e.message||"Could not delete account")}finally{setDeleteBusy(false)}};
 const stats=useMemo(()=>({total:orders.reduce((s,o)=>s+Number(o.total||0),0),delivered:orders.filter(o=>String(o.status)==="delivered").length,count:orders.length}),[orders]);
 const recent=orders.slice(0,3);
 if(mode!=="profile"||!user)return <div className="page account-page"><div className="page-head"><span>THE OFF GRID / ACCOUNT</span><h1>{forgot?<>RESET <em>PASSWORD.</em></>:mode==="login"?<>GET <em>IN.</em></>:<>JOIN THE <em>GRID.</em></>}</h1></div>{!forgot&&<div className="auth-tabs"><button className={mode==="login"?"active":""} onClick={()=>{setMode("login");setErr("")}}>LOGIN</button><button className={mode==="register"?"active":""} onClick={()=>{setMode("register");setErr("")}}>REGISTER</button></div>}{forgot?<form className="login-form account-auth-card" onSubmit={sendReset}><p>Enter your account email and we'll send password reset instructions.</p><input required type="email" placeholder="EMAIL" value={forgotEmail} onChange={e=>setForgotEmail(e.target.value)}/>{err&&<p className="notify-me-error">{err}</p>}<button className="orange-btn" disabled={busy}>{busy?"SENDING...":"SEND RESET LINK"}</button><button type="button" className="text-button auth-toggle" onClick={()=>setForgot(false)}>BACK TO SIGN IN</button></form>:mode==="login"?<form className="login-form account-auth-card" onSubmit={login}><div className="account-auth-intro"><UserRound size={22}/><span>MEMBERS GET MORE</span></div><input required type="email" placeholder="EMAIL" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/><input required type="password" placeholder="PASSWORD" value={f.password} onChange={e=>setF({...f,password:e.target.value})}/>{err&&<p className="notify-me-error">{err}</p>}<button className="orange-btn" disabled={busy}>{busy?"SIGNING IN...":"SIGN IN"}</button><button type="button" className="text-button" onClick={()=>{setForgot(true);setForgotEmail(f.email);setErr("")}}>FORGOT PASSWORD?</button><button type="button" className="text-button auth-toggle" onClick={()=>{setMode("register");setErr("")}}>NEW HERE? CREATE AN ACCOUNT</button></form>:<form className="login-form account-auth-card" onSubmit={register}><input required placeholder="NAME" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><input required type="email" placeholder="EMAIL" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/><input required type="password" placeholder="PASSWORD (6+ CHARACTERS)" value={f.password} onChange={e=>setF({...f,password:e.target.value})}/><input placeholder="REFERRAL CODE (OPTIONAL)" value={f.referral_code} onChange={e=>setF({...f,referral_code:e.target.value})}/>{err&&<p className="notify-me-error">{err}</p>}<button className="orange-btn" disabled={busy}>{busy?"CREATING ACCOUNT...":"CREATE ACCOUNT"}</button><button type="button" className="text-button auth-toggle" onClick={()=>{setMode("login");setErr("")}}>ALREADY HAVE AN ACCOUNT? SIGN IN</button></form>}</div>;
 return <div className="page account-page"><div className="page-head account-head"><span>THE OFF GRID / ACCOUNT</span><div className="account-head-row"><div><h1>WELCOME, <em>{user.name||"YOU"}.</em></h1><p className="account-member-line">{profile?.email||user.email} {profile?.role==="admin"&&<b>ADMIN</b>}</p></div><button className="text-button" onClick={signOut}><LogOut size={15}/> SIGN OUT</button></div></div>{notice&&<div className="account-notice account-notice-wide">{notice}</div>}<div className="account-dashboard"><aside className="account-sidebar"><button className={tab==="overview"?"active":""} onClick={()=>setTab("overview")}><UserRound/> OVERVIEW</button><button className={tab==="orders"?"active":""} onClick={()=>setTab("orders")}><Package/> ORDERS <b>{stats.count}</b></button><button className={tab==="addresses"?"active":""} onClick={()=>setTab("addresses")}><MapPin/> ADDRESSES <b>{addresses.length}</b></button><button onClick={()=>nav("/wishlist")}><Heart/> WISHLIST</button><button className={tab==="returns"?"active":""} onClick={()=>setTab("returns")}><RefreshCw/> RETURNS <b>{returns.length}</b></button><button className={tab==="rewards"?"active":""} onClick={()=>setTab("rewards")}><Star/> REWARDS</button><button className={tab==="profile"?"active":""} onClick={()=>setTab("profile")}><ShieldCheck/> PROFILE</button></aside><main className="account-content">
 {tab==="overview"&&<><div className="account-stat-grid"><div><span>ORDERS</span><strong>{stats.count}</strong></div><div><span>DELIVERED</span><strong>{stats.delivered}</strong></div><div><span>LIFETIME SPEND</span><strong>{money(stats.total)}</strong></div><div><span>GRID POINTS</span><strong>{Number(profile?.loyalty_points||0)}</strong></div></div><section className="account-panel account-rewards-strip"><div><span>THE OFF GRID REWARDS</span><h2>{Number(profile?.loyalty_points||0)} <em>POINTS.</em></h2><p>Earn points as you shop and use them toward future orders.</p></div><button className="outline-btn" onClick={()=>setTab("rewards")}>VIEW REWARDS <ArrowRight size={15}/></button></section><section className="account-panel"><div className="account-panel-head"><div><span>RECENT ORDERS</span><h2>YOUR LATEST <em>BUYS.</em></h2></div><button className="text-button" onClick={()=>setTab("orders")}>VIEW ALL <ArrowRight size={15}/></button></div>{recent.length?<div className="account-mini-orders">{recent.map(o=><div key={o.id}><div><strong>OG{String(o.id).padStart(6,"0")}</strong><span>{o.created_at?new Date(o.created_at).toLocaleDateString("en-IN"):"—"}</span></div><p>{Array.isArray(o.items)?o.items.slice(0,2).map(i=>i.name).join(", "):"THE OFF GRID ORDER"}</p><b>{money(o.total)}</b><button onClick={()=>nav(`/track-order/${o.id}`)}>TRACK <ArrowRight size={14}/></button></div>)}</div>:<div className="account-empty"><Package size={25}/><h3>NO ORDERS YET.</h3><button className="orange-btn" onClick={()=>nav("/")}>START SHOPPING</button></div>}</section></>}
 {tab==="orders"&&<section className="account-panel"><div className="account-panel-head"><div><span>ORDER HISTORY</span><h2>ALL YOUR <em>ORDERS.</em></h2></div><RefreshCw className={busy?"spin":""} size={18} onClick={refreshAccount}/></div>{orders.length?<div className="account-order-list">{orders.map(o=><article key={o.id}><div className="account-order-top"><div><strong>OG{String(o.id).padStart(6,"0")}</strong><span>{o.created_at?new Date(o.created_at).toLocaleDateString("en-IN"):"—"}</span></div><span className={`order-status ${o.status}`}>{String(o.status||"pending").toUpperCase()}</span></div><h3>{Array.isArray(o.items)&&o.items.length?o.items.map(i=>`${i.name}${i.quantity>1?` × ${i.quantity}`:""}`).join(", "):"THE OFF GRID ORDER"}</h3><div className="account-order-meta"><span>{money(o.total)}</span><span>{String(o.payment_method||"COD").toUpperCase()}</span>{o.points_earned>0&&<span>+{o.points_earned} POINTS</span>}</div><div className="account-order-actions">{o.status!=="cancelled"&&<button className="text-button" onClick={()=>nav(`/track-order/${o.id}`)}>TRACK ORDER <ArrowRight size={14}/></button>}{o.status==="pending"&&String(o.payment_method||"").toLowerCase()==="cod"&&<button className="text-button" onClick={()=>window.confirm("Cancel this order?")&&window.dispatchEvent(new CustomEvent("offgrid-cancel-order",{detail:o.id}))}>CANCEL ORDER</button>}</div></article>)}</div>:<div className="account-empty"><Package size={25}/><h3>NO ORDERS YET.</h3><button className="orange-btn" onClick={()=>nav("/")}>SHOP THE COLLECTION</button></div>}</section>}
 {tab==="addresses"&&<><section className="account-panel"><div className="account-panel-head"><div><span>SAVED DELIVERY DETAILS</span><h2>YOUR <em>ADDRESSES.</em></h2></div><button className="orange-btn" onClick={()=>startAddress()}>ADD ADDRESS</button></div>{addresses.length?<div className="saved-address-grid">{addresses.map(a=><article key={a.id} className={a.is_default?"default":""}><div className="saved-address-top"><strong>{a.label}</strong>{a.is_default&&<span>DEFAULT</span>}</div><h3>{a.name}</h3><p>{a.phone}<br/>{a.address}<br/>{a.city}, {a.state} — {a.pincode}</p><div><button className="text-button" onClick={()=>startAddress(a)}>EDIT</button>{!a.is_default&&<button className="text-button" onClick={()=>makeDefault(a.id)}>SET DEFAULT</button>}<button className="text-button" onClick={()=>removeAddress(a.id)}>REMOVE</button></div></article>)}</div>:<div className="account-empty"><MapPin size={25}/><h3>NO SAVED ADDRESSES.</h3><p>Save an address once and checkout faster next time.</p></div>}</section>{(editing||addresses.length===0)?<section className="account-panel account-address-form"><div className="account-panel-head"><div><span>{editing?"EDIT ADDRESS":"NEW ADDRESS"}</span><h2>{editing?"UPDATE YOUR":"ADD A"} <em>ADDRESS.</em></h2></div></div><form onSubmit={saveAddress}><div className="account-form-grid"><input required placeholder="LABEL (HOME / WORK)" value={address.label} onChange={e=>setAddress({...address,label:e.target.value})}/><input required placeholder="FULL NAME" value={address.name} onChange={e=>setAddress({...address,name:e.target.value})}/><input required placeholder="PHONE" inputMode="numeric" maxLength={10} value={address.phone} onChange={e=>setAddress({...address,phone:e.target.value})}/><input required placeholder="PINCODE" inputMode="numeric" maxLength={6} value={address.pincode} onChange={e=>setAddress({...address,pincode:e.target.value})}/><input required className="account-form-wide" placeholder="ADDRESS" value={address.address} onChange={e=>setAddress({...address,address:e.target.value})}/><input required placeholder="CITY" value={address.city} onChange={e=>setAddress({...address,city:e.target.value})}/><input required placeholder="STATE" value={address.state} onChange={e=>setAddress({...address,state:e.target.value})}/><label className="account-default-check"><input type="checkbox" checked={Boolean(address.is_default)} onChange={e=>setAddress({...address,is_default:e.target.checked})}/> MAKE DEFAULT</label></div><div><button className="orange-btn" disabled={addressBusy}>{addressBusy?"SAVING...":"SAVE ADDRESS"}</button>{editing&&<button type="button" className="text-button" onClick={()=>{setEditing(null);setAddress(emptyAddress)}}>CANCEL</button>}</div></form></section>:null}</>}
 {tab==="returns"&&<section className="account-panel"><div className="account-panel-head"><div><span>RETURNS & EXCHANGES</span><h2>YOUR <em>REQUESTS.</em></h2></div></div>{returns.length?<div className="account-order-list">{returns.map(r=><article key={r.id}><div className="account-order-top"><div><strong>{r.type==="exchange"?"EXCHANGE":"RETURN"} — OG{String(r.order_id).padStart(6,"0")}</strong><span>{r.created_at?new Date(r.created_at).toLocaleDateString("en-IN"):"—"}</span></div><span className={`order-status return-status-${r.status}`}>{String(r.status).toUpperCase()}</span></div><h3>{r.reason}</h3>{r.exchange_size&&<p>Requested size: {r.exchange_size}</p>}{r.admin_notes&&<p className="muted">{r.admin_notes}</p>}{r.type==="exchange"&&r.replacement_status&&<div className="replacement-tracking"><span>REPLACEMENT: {r.replacement_status.toUpperCase()}</span>{r.replacement_courier&&<p>{r.replacement_courier}{r.replacement_awb?` · AWB ${r.replacement_awb}`:""}</p>}{r.replacement_tracking_url&&<a href={r.replacement_tracking_url} target="_blank" rel="noreferrer">TRACK REPLACEMENT</a>}</div>}</article>)}</div>:<div className="account-empty"><Package size={25}/><h3>NO RETURN OR EXCHANGE REQUESTS.</h3><p>You can request a return or exchange from a delivered order within 10 days.</p></div>}</section>}
 {tab==="rewards"&&<section className="account-panel"><div className="account-panel-head"><div><span>LOYALTY PROGRAM</span><h2>STAY <em>OFF GRID.</em></h2></div><Star size={25}/></div><div className="rewards-hero"><strong>{Number(profile?.loyalty_points||0)}</strong><span>GRID POINTS</span><p>Earn 1 point for every ₹100 spent. Use your points as a discount on future purchases.</p></div></section>}
 {tab==="profile"&&<section className="account-panel"><div className="account-panel-head"><div><span>MEMBER PROFILE</span><h2>YOUR <em>DETAILS.</em></h2></div>{!editProfile&&<button className="text-button" onClick={startEditProfile}>EDIT PROFILE</button>}</div>{editProfile?<form className="account-form-grid profile-edit-form" onSubmit={saveProfile}><input required placeholder="NAME" value={pf.name} onChange={e=>setPf({...pf,name:e.target.value})}/><input required type="email" placeholder="EMAIL" value={pf.email} onChange={e=>setPf({...pf,email:e.target.value})}/><input type="password" placeholder="NEW PASSWORD (LEAVE BLANK TO KEEP CURRENT)" value={pf.new_password} onChange={e=>setPf({...pf,new_password:e.target.value})}/>{pf.new_password&&<input required type="password" placeholder="CURRENT PASSWORD (TO CONFIRM)" value={pf.current_password} onChange={e=>setPf({...pf,current_password:e.target.value})}/>}{pfErr&&<p className="notify-me-error">{pfErr}</p>}<div><button className="orange-btn" disabled={pfBusy}>{pfBusy?"SAVING...":"SAVE CHANGES"}</button><button type="button" className="text-button" onClick={()=>setEditProfile(false)}>CANCEL</button></div></form>:<div className="profile-details"><div><span>NAME</span><strong>{profile?.name||user.name}</strong></div><div><span>EMAIL</span><strong>{profile?.email||user.email}</strong></div><div><span>REFERRAL CODE</span><strong>{profile?.referral_code||"—"}</strong><button className="text-button" onClick={copyReferral}><Copy size={14}/> COPY CODE</button><button className="text-button" onClick={shareReferralWhatsapp}>SHARE ON WHATSAPP</button></div><div><span>REFERRALS</span><strong>{profile?.referral_count||0}</strong></div></div>}<div className="account-danger-zone">{!deleteOpen?<button type="button" className="text-button danger-link" onClick={()=>setDeleteOpen(true)}>DELETE ACCOUNT</button>:<form className="account-form-grid" onSubmit={deleteAccount}><p className="notify-me-error">This permanently deletes your account, addresses, wishlist, and cart. Your past orders are kept for accounting records but disconnected from your account. This cannot be undone.</p><input required type="password" placeholder="ENTER YOUR PASSWORD TO CONFIRM" value={deletePassword} onChange={e=>setDeletePassword(e.target.value)}/>{deleteErr&&<p className="notify-me-error">{deleteErr}</p>}<div><button className="orange-btn danger-btn" disabled={deleteBusy}>{deleteBusy?"DELETING...":"PERMANENTLY DELETE MY ACCOUNT"}</button><button type="button" className="text-button" onClick={()=>{setDeleteOpen(false);setDeletePassword("");setDeleteErr("")}}>CANCEL</button></div></form>}</div></section>}
 </main></div></div>;
}
